# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-03-11 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20181006_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '统计',
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': '地址管理'},
        ),
        migrations.AlterModelOptions(
            name='axfuser',
            options={'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': '购物车'},
        ),
        migrations.AlterModelOptions(
            name='foodtype',
            options={'verbose_name_plural': '商品类别'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='mainmustbuy',
            options={'verbose_name_plural': '必买商品配置'},
        ),
        migrations.AlterModelOptions(
            name='mainnav',
            options={'verbose_name_plural': '首页展示'},
        ),
        migrations.AlterModelOptions(
            name='mainshop',
            options={'verbose_name_plural': '主要商铺'},
        ),
        migrations.AlterModelOptions(
            name='mainshow',
            options={'verbose_name_plural': '主要展示'},
        ),
        migrations.AlterModelOptions(
            name='mainwheel',
            options={'verbose_name_plural': '轮播配置'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='orderaddress',
            options={'verbose_name_plural': '订单地址管理'},
        ),
        migrations.AlterModelOptions(
            name='ordergoods',
            options={'verbose_name_plural': '订单商品'},
        ),
    ]
